### ISSUE TITLE
is the zip and enumerate tutorial complete? 

### ISSUE THREAD

**Issue by anikk94** [Akuli/python-tutorial#10]
zip and enumerate are not explained at all...
i see them used in the answers, but i had to look them up to make sense of them, was that expected?

**Comment by Akuli** [comment]
My tutorial contains a link to another tutorial online. Did you read that?

I could write my own zip and enumerate tutorial, too.

**Comment by anikk94** [comment]
Sorry about that, I saw it upon revisiting it. Really appreciate the tutorial though. Would help if you could explain what the 'TODO' parts are (are they future additions to the tutorial?)

**Comment by Akuli** [comment]
The TODO parts are things that aren't complete. It's common to write comments like `# TODO: blah blah`.

**Comment by tusharkhatriofficial** [comment]
Do you want me to complete this Enumerate Tutorial?

**Comment by Akuli** [comment]
Sure :) Make a fork, edit the file on your fork, and then make a pull request of your edits. GitHub mostly guides you to do all this if you just click the edit button.

**Comment by Akuli** [comment]
This too was done.
