### ISSUE TITLE
attributeError

### ISSUE THREAD

**Issue by sumankumari08** [Akuli/python-tutorial#16]
class TutorialRenderer(mistune.Renderer):
AttributeError: module 'mistune' has no attribute 'Renderer'

please resolve this problem

**Comment by Akuli** [comment]
If you are always connected to the internet, you don't need to run `make-html.py` at all, and you can instead just read the tutorial directly off of github. Go to https://github.com/Akuli/python-tutorial/ and scroll down past the list of files. You will see a list of contents there.

You seem to be running `py make-html.py` or `python3 make-html.py`? Try running just `py` or `python3`. This should give you a `>>>` prompt. Type these commands there:

```
>>> import mistune
>>> mistune.__version__
```

What does that say?
