### ISSUE TITLE
switch to python >=3.7 and use f-strings

### ISSUE THREAD

**Issue by Akuli** [Akuli/python-tutorial#19]

**Comment by sam4u3** [comment]
Use github project feature to manage this project with kan-ban strategy

**Comment by sachindavra** [comment]
Hi @Akuli , could you describe what needs to be changed?

**Comment by Akuli** [comment]
- f strings in `handy-stuff-strings.md`
- add dataclasses to `advanced/datatypes.md`, consider removing named tuples
- anything else I forgot?

**Comment by laysauchoa** [comment]
is someone working on this already? I want to help!

**Comment by Akuli** [comment]
Just do it then :) If multiple people do it, I will combine the changes.

**Comment by tusharkhatriofficial** [comment]
I'm working on this if you have any updates please let me know.

**Comment by Akuli** [comment]
Nice :)

Don't add dataclasses yet. I probably want to restructure things a bit before adding dataclasses. Basically, I think the basics/advanced splitting as it is now doesn't make much sense, and it would be better to have something like basics/intermediate where intermediate would contain things like list/dict/set comprehensions, dataclasses, inheritance, typing, and so on.

**Comment by tusharkhatriofficial** [comment]
**Intermediate section** is indeed a good idea!

**Comment by tusharkhatriofficial** [comment]
Do you want to replace the old method with `f-Strings` or just add an extra `f-Strings` section?

**Comment by Akuli** [comment]
We don't need `.format()` or `%` formatting anymore, at least not in the basics section.

**Comment by Akuli** [comment]
There's still `%` formatting in these files:
```
advanced/functions.md
advanced/magicmethods.md
basics/answers.md
basics/defining-functions.md
basics/exceptions.md
basics/larger-program.md
basics/loops.md
basics/modules.md
```

**Comment by tusharkhatriofficial** [comment]
sure, I'll replace them asap

**Comment by Akuli** [comment]
This is done now. Thanks @tusharkhatriofficial for working on this!
