### ISSUE TITLE
editor-setup.md is too opinionated

### ISSUE THREAD

**Issue by Akuli** [Akuli/python-tutorial#33]
It is saying "these editors are BAD" and listing a bunch of common editors. It's just not a good thing.

**Comment by georgerahul24** [comment]
Hey, can I work on this?

**Comment by Akuli** [comment]
Sure. We should probably just delete the list of bad editors and instead say it doesn't really matter which editor you use, as long as it can be used to write and run a `.py` file.

**Comment by georgerahul24** [comment]
I have submitted [a pull request](https://github.com/Akuli/python-tutorial/pull/46) for the same. Hope it solves the issue.
