### ISSUE TITLE
Hacktoberfest-Related.

### ISSUE THREAD

**Issue by thegeekyb0y** [Akuli/python-tutorial#42]
Why dont you create this repo up for hacktober fest contributions? 
Its easy.

Here is how you do it: https://hacktoberfest.com/participation/#maintainers

**Comment by tusharkhatriofficial** [comment]
hi! @thegeekyb0y  I've a repo ready to participate this October. I've something really amazing going in my head. hacktoberfest can help me achieve that... This time is the best to attract many open-source enthusiasts.

**Comment by Akuli** [comment]
Pull requests to this repo tend to take quite a lot of time to review, so I won't set it up, at least not right now. But thanks for reminding me about hacktoberfest. I'm currently setting up hacktoberfest for one of my other projects.
