### ISSUE TITLE
Iterating the iterated list in python

### ISSUE THREAD

**Issue by GirishMadheswaran** [Akuli/python-tutorial#47]
first = []
second = [] 
for i in range(len(fruits)): 
                first.append(fruits[i]) 
            #after this method i am getting the output like below 
            ["orange", "apple", "banana"] 
            for item in range(len(first)): 
                print(first[item]) 
            # after this method i am getting the output like this 
orange
apple
banana 
             #i am trying to store the above values inside the second=[]
Need an solution for this

**Comment by Akuli** [comment]
One easy way to add all items is with `.extend()`, see https://github.com/Akuli/python-tutorial/blob/master/basics/lists-and-tuples.md#what-can-we-do-with-lists

```
fruits = ['orange', 'apple', 'banana']
second = []
second.extend(fruits)
print(second)  # Output: ['orange', 'apple', 'banana']
```

**Comment by Niki-098** [comment]
second=first.copy()
print(second)
