### ISSUE TITLE
Permission to use your tutorial in my app

### ISSUE THREAD

**Issue by LincCodes** [Akuli/python-tutorial#51]
I am building an android app which needs a python tutorial.

With that said, can I use your tutorial?

**Comment by Akuli** [comment]
You can use my tutorial as long as:
- you mention that it is written by me
- if you change the tutorial, you need to mention that you have changed it
- you include at least the first half of the `LICENSE` file with it.

See the `LICENSE` file for details, or ask me if something is unclear :)
