### ISSUE TITLE
One little obstacle

### ISSUE THREAD

**Issue by hupoci0000** [Akuli/python-tutorial#8]
Hello Akuli

I am doing the exercise for if else/elif

print('Hello!')
something = input("Enter something: ")
if something = 'hello':
    print("Hello for you too!")

elif something = 'hi'
    print('Hi there!')
else:
    print("I don't know what," something, "means.")

I ve fixed the errors in the block, but having trouble to fix the last else-print-clause, when i run it, no results, and no error message, it stuck. Please help.

btw, wonderful tutorial.

Thanks much

Tony

**Comment by Akuli** [comment]
The code you have here seems to be the broken code from my tutorial. Can you show your mostly-fixed version of the code?

By the way, if you put the code between backticks, like this...

    ```
    some code
    ```

...it'll show up correctly and I can actually see how you have indented it.

**Comment by Aliraza-N** [comment]
If your code is exactly how you copy/pasted it out to be, then it's incorrect. Notice in the last print statement, your first comma goes before the end quote, where instead it should be after. 

print("I don't know what," something, "means.") 
should be: 
print("I don't know what", something, "means.")

**Comment by hupoci0000** [comment]
Thanks guys, i think i've resolved it. haha.

**Comment by Akuli** [comment]
Nice
