### ISSUE TITLE
CONFUSED

### ISSUE THREAD

**Issue by SOCSECADM** [Akuli/python-tutorial#9]
I BEGAN YOUR "BASIC' TUTORIAL AND WORKED UP TO EDITOR. YOU SUGGESTED PORCUPINE AND MENTIONED SOME NEW TERMS LIKE TERMINAL; AND SAID IF YOU DON'T UNDERSTAND THESE TERMS, CLICK  HERE AND THEN I GOT COMPLETELY LOST.

PS. I am a retired chemistry professor and learning to code as a way to interact with my very smart 15 yr old grandson. And keep my brain active. It has been long time since I used Fortran.

**Comment by Akuli** [comment]
I think you mean this link with the "click here": https://github.com/Akuli/python-tutorial/blob/master/basics/installing-python.md

How does that link make you completely lost? How did you install python? Which operating system are you using (e.g. windows)?
